# Dependabot configuration for automated dependency updates
version: 2
updates:
  # Update .NET packages
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    open-pull-requests-limit: 10
    reviewers:
      - "dependabot[bot]"
    assignees:
      - "dependabot[bot]"
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
    labels:
      - "dependencies"
      - "dotnet"
    # Group minor and patch updates
    groups:
      minor-and-patch:
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"
      security-updates:
        applies-to: security-updates
    # Ignore specific packages if needed
    ignore:
      # Ignore major version updates for breaking changes
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
      # Add specific packages to ignore here if needed
      # - dependency-name: "package-name"
      #   versions: ["1.x", "2.x"]
    
  # Update GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
